---
apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
type: Opaque
data:
  secret-token: V2E0S2R1NmhNdDN0WUttNGpiOXA0dlpVdWM3akJWRnc=
  database-url: cG9zdGdyZXNxbDovL2Rya2lxOnRlc3RAcG9zdGdyZXM6NTQzMi9kcmtpcQ==
  postgres-user: ZHJraXE=
  postgres-password: dGVzdA==
