apiVersion: batch/v1
kind: Job
metadata:
  generateName: reset-databse
spec:
  template:
    spec:
      restartPolicy: "Never" 
      containers:
      - name: migrations
        image: emohamed13/ruby-drkiq:latest
#        command: ["rake db:create && rake db:migrate"]
        command:
        - /bin/sh
        - -c
        - rake db:reset && rake db:migrate
        env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: database-url
            - name: SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: secret-token
            - name: CACHE_URL
              valueFrom:
                configMapKeyRef:
                  key: CACHE_URL
                  name: env-config
            - name: JOB_WORKER_URL
              valueFrom:
                configMapKeyRef:
                  key: JOB_WORKER_URL
                  name: env-config
            - name: LISTEN_ON
              valueFrom:
                configMapKeyRef:
                  key: LISTEN_ON
                  name: env-config
            - name: WORKER_PROCESSES
              valueFrom:
                configMapKeyRef:
                  key: WORKER_PROCESSES
                  name: env-config
